version: '3.8'
services:
  app:
    build: .
    image: maryam271291/sit323-737-2024-t1--prac7p
    ports:
      - '3043:3040'
    environment:
      - PORT=3043
    container_name: my-app4
    networks:
      - my-net

  app1:
    build: .
    image: maryam271291/sit323-737-2024-t1--prac7p
    ports:
      - '3044:3040'
    environment:
      - PORT=3044
    container_name: my-app3
    networks:
      - my-net


networks:
  my-net:
    driver: bridge